trigger:
- main


variables:
  - group: 'pipeline-variables'

  - name: dockerComposeFile
    value: '**/docker-compose.yml'

  - name: appName
    value: 'comentariosapp'

  - name: aciExposePort
    value: '8000'


stages:

# Build Docker Image and Push to DockerHub
- stage: Build
  displayName: Build and push Container Image
  jobs:
    - job: Build
      displayName: Build
      pool:
        vmImage: ubuntu-latest

      steps:
      - task: DockerCompose@0
        displayName: 'Build services $(appName)'
        inputs:
          containerregistrytype: 'Container Registry'
          dockerComposeFile: $(dockerComposeFile)
          qualifyImageNames: false
          action: 'Build services'

      - task: Bash@3
        displayName: Docker tag image
        inputs:
          targetType: 'inline'
          script: docker tag $(appName) $(DockerHubNamespace)/$(appName)

      - task: Docker@2
        displayName: 'Push docker image to DockerHub'
        inputs:
          containerRegistry: $(DockerHubServiceConnection)
          repository: $(DockerHubNamespace)/$(appName)
          tags: 'latest'
          command: push


# Deploy Docker Image to ACI (IaC)
- stage: Deploy
  displayName: Deploy to ACI
  dependsOn: [Build]
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest

    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      displayName: 'ARM Template deployment: ACI'
      inputs:
        azureResourceManagerConnection: $(AzureServiceConnection)
        subscriptionId: $(AzureSubscriptionId)
        resourceGroupName: $(AzureResourceGroupName)
        location: $(AzureResourceLocation)
        csmFile: '$(System.DefaultWorkingDirectory)/**/iac/aci/aci_template.json'
        overrideParameters: '-app_name "$(appName)" -dockerhub_namespace "$(DockerHubNamespace)" -aci_expose_port $(aciExposePort)'
        deploymentName: 'aci-$(appName)-deploy'
